# Generated by Django 3.2.8 on 2022-06-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blog_image', models.FileField(blank=True, null=True, upload_to='images')),
                ('blog_category', models.CharField(choices=[('Mental Health', 'Andaman and Nicobar Islands'), ('Heart Disease', 'Heart Disease'), ('COVID19', 'COVID19'), ('Immunization', 'Immunization')], max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('is_draft', models.BooleanField(default=True)),
            ],
        ),
    ]
