# Generated by Django 3.2.8 on 2022-06-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('COVID19', 'COVID19'), ('Immunization', 'Immunization')], max_length=100),
        ),
    ]
