# Generated by Django 3.2.8 on 2022-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_blog_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Is Draft?'),
        ),
    ]
